# Generated by Django 4.2.5 on 2023-09-25 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0002_trainedimage_embeddings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedFace',
            fields=[
                ('face_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.ImageField(upload_to='detected_faces/')),
                ('confidence', models.CharField(max_length=200)),
                ('bounding_box', models.TextField(null=True)),
                ('keypoints', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestImage',
        ),
        migrations.DeleteModel(
            name='TrainedImage',
        ),
    ]
