# Generated by Django 4.2.5 on 2023-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0003_detectedface_delete_testimage_delete_trainedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='DetectedFace',
        ),
    ]
