# Generated by Django 4.2.5 on 2023-09-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0004_recognizedperson_delete_detectedface'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('face_features', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RecognizedPerson',
        ),
    ]
