# Generated by Django 4.2.5 on 2023-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0006_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=b'', upload_to='captured_images/'),
            preserve_default=False,
        ),
    ]
